require:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
  NewCops: enable
