# Download the latest Ruby patch versions, install dependencies, and run tests.
name: test
on:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
jobs:
  test:
    environment: staging
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby-version }}
    strategy:
      matrix:
        ruby-version: [3.2]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Prepare db
      run: bundle exec rake db:prepare RAILS_ENV=test
    - name: Run tests
      run: bundle exec rspec
    - name: Send Code Climate coverage
      uses: aktions/codeclimate-test-reporter@v1
      with:
        codeclimate-test-reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}
        command: after-build --coverage-input-type lcov
    - name: Send Coveralls coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run RuboCop
      run: bundle exec rubocop
    - name: Run Inch
      run: bundle exec inch --pedantic
