# Download the latest Ruby patch versions, install dependencies, and run tests.
name: test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    environment: staging
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.7]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install dependencies
      run: bundle install
    - name: Prepare db
      run: bundle exec rake db:prepare RAILS_ENV=test
    - name: Rubocop checks
      uses: gimenete/rubocop-action@1.0
    - name: Run tests
      run: bundle exec rake
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
