name: Test
on:
  push:
permissions: read-all
jobs:
  test:
    environment: staging
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby-version }}
    strategy:
      matrix:
        ruby-version: [3.3]
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: ruby/setup-ruby@a2bbe5b1b236842c1cb7dd11e8e3b51e0a616acc
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - run: bundle exec rake db:prepare RAILS_ENV=test
    - run: bundle exec rspec
    - run: bundle exec rubocop
    - run: bundle exec inch --pedantic
    - uses: qltysh/qlty-action/coverage@v1
      with:
        oidc: true
        files: COVERAGE_FILE_PATH # e.g. coverage/lcov.info
    - uses: coverallsapp/github-action@cfd0633edbd2411b532b808ba7a8b5e04f76d2c8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
